skip_validation: 4
aug_strength: 2
model: 'google/matcha-base'
max_length: 512
epochs: 10
optimizer:
  name: torch.optim.AdamW
  weight_decay: 0.01
  params:
    lr: 3.0e-05
    eps: 1.0e-06
    betas: [0.9, 0.999]
scheduler:
  name: cosine
  params:
    num_cycles: 0.25
  interval: step
  warmup: 0.1
train_loader:
  batch_size: 1
  drop_last: true
  num_workers: 1
  pin_memory: false
  shuffle: true
val_loader:
  batch_size: 1
  drop_last: false
  num_workers: 1
  pin_memory: false
  shuffle: false
trainer:
  devices: 4
  accumulate_grad_batches: 4
  fast_dev_run: false
  num_sanity_val_steps: 0
  precision: 16-mixed
  val_check_interval: 0.25
  gradient_clip_val: 1.0